<section class="tos space">
	<div class="container">
		<div class="row">
			<div class="col-sm-10 col-sm-offset-1">
				<h2 class="title-head" style="padding-bottom: 20px;margin-bottom: 20px;border-bottom: 1px solid #EEE;">服务条款</h2>
				版本信息: UTC+8 2018-3-1 10:39 TOS Version 0.004D<br><br>*下文BlueAirHost意味着本站(www.kvm.ink, cn.blueairhost.xyz), 隶属于<a title="形随意动官网" href="http://www.xsyds.cn/" target="_blank">形随意动科技团队(www.xsyds.cn)</a><br>BlueAirHost成立于2017年, 秉承着安全可靠, 高速廉价的信念为客户提供安心和高速的互联网主机租用服务.<br>BlueAirHost希望您在购买产品之前, 仔细熟读并理解这些须知, 以避免我们和您造成的未来纠纷和误解, 甚至经济损失.<br><br><span style="font-size: medium;"><span style="font-size: large;">服务类</span><br></span>1. BlueAirHost作为一个廉价主机服务, 所有我们出售的主机都是自我管理的, 不存在任何使用其他主机商分销的情况(除非我们在购物车中标注). 然而, 当我们在努力的提高您的产品稳定性和您的体验的同时, 您需要自我管理您购买的主机, 除去主机自身问题, 其他一系列安装辅助, bug排查皆不提供免费服务, 如果需要请另行购买附加服务.<br>2. 在日常使用中, 请自我管理您的主机服务, 并且定期备份. <br>a) BlueAirHost不对任何形式的<strong>免费主机数据丢失</strong>负任何性质的责任, 用户也不能因此诋毁BlueAirHost<br>b) BlueAirHost不对<strong>不可抗力因素造成的服务停止, 和数据丢失</strong>负任何性质的责任, 包括但不限于黑客攻击, 地质灾害, 设备损坏, 等等.<br>3. 如果您准备停止使用免费主机, 请您在您的客户中心中的特定主机页面, 点击"请求取消", 填入您的请求取消原因.<br>4. BlueAirHost有权在任何情况下停止您的服务, 停止的原因包含但不限于以下内容:<br>&nbsp;&nbsp;&nbsp; 1) 黄色, 暴力, 博彩, 侵占版权, 擦边球等任何违反国家法律法规内容, 一经发现永久停用账号 + 删除主机账户 + 向其他主机商提交黑名单<br>&nbsp;&nbsp;&nbsp; 2) 广告, 主机的网站广告覆盖率不应高于35%<br>&nbsp;&nbsp;&nbsp; 3) 秒赞,采集等高占用的程序.(此条不适用于产品介绍中明确说明可以搭建秒赞/采集程序的产品)<br>&nbsp;&nbsp;&nbsp; 4) 涉及人身攻击, 政治隐喻的内容<br>&nbsp; &nbsp; 5) 主机滥用(如未成功绑定域名), 主机占用过高<br>5. 反滥用细则:<br>&nbsp;&nbsp;&nbsp; *新购免费主机用户有1个星期的免检查接入时间<br>&nbsp;&nbsp;&nbsp; 1) 主机的域名DNS记录必须指向主机服务器IP地址, 如果使用了CDN内容分发服务, 用户必须在官网首页可见的地方, 增加友情链接, 友链细则见此类第6条.<br>&nbsp;&nbsp;&nbsp; 2) 您的官网首页必须可以访问, 这是为了方便我们对您的网站内容进行审查.<br>&nbsp;&nbsp;&nbsp; 3) 如果您的主机绑定域名变更, 您需要以工单/QQ私聊的方式通知客户服务人员, 以便我们对您的服务信息进行更改, 同时让我们可以审查您的新滥用情况.<br>&nbsp;&nbsp;&nbsp; 4) 由于我们检查到过擦边球网站, 从11月2日起, 任何域名解析出现NXDOMAIN的, 一律直接删除主机, 不予2星期整改 / 备份数据时间.<br>6. 如果您的网站是以下内容的, 且网站由我们提供<span style="font-size: medium;"><strong>免费服务</strong></span>, 请在网站底部添加友情链接, 必须首页可见<br>&nbsp;&nbsp;&nbsp; 1) IDC站点(包括但不限于 IaaS, PaaS, 部分SaaS可算在内)<br>&nbsp;&nbsp;&nbsp; 2) 任意添加了任意CDN服务的站点(这是为了防滥用系统审核您的网站域名指向正确)<br>&nbsp;&nbsp;&nbsp; ＊ 其他站点不强制友链, 如果您认为我们的服务器好用可靠, 并且自愿加入友链, 那么请便<br>&nbsp;&nbsp;&nbsp; ＊ 形随意动 / BlueAirHost愿与您携手共创更优质的互联网环境. 我们会不定期给予部分自愿加入友链的<strong>优质</strong><strong>站点</strong>升级付费节点.<br>&nbsp;&nbsp;&nbsp; <strong>代码可选择下列任意一种(只需要一种, 不需要加2-3个友链)</strong><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;p&gt;Powered by &lt;a href="http://www.kvm.ink/" target="_blank"&gt;BlueAirHost&lt;/a&gt;&lt;/p&gt;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;p&gt;&lt;a href="http://www.kvm.ink/" target="_blank"&gt;稳定, 安心的廉价主机服务&lt;/a&gt;&lt;/p&gt;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;p&gt;&lt;a href="http://www.xsyds.cn/" target="_blank"&gt;形随意动&lt;/a&gt;&lt;/p&gt;<br><span style="font-size: medium;"><span style="font-size: large;"><br>通知类</span><br></span>1. BlueAirHost有时会不定期对部分节点进行维护重启等操作, 如果您想要及时了解详细情况, 您需要加入我们的官方QQ群, 251391969, 同时关注官网最新的通知<br>2. BlueAirHost会不定期对您网站的内容进行审核, 遇到不符合TOS要求的, 情节严重者不与通告, 直接删除主机.<br>3. BlueAirHost可能会并有权在不通知您的情况下不定期对服务条款进行更新, 您需要自行定期查阅TOS, 来继续使用BlueAirHost提供的服务.<br><br>最后, 感谢您选择BlueAirHost, 我们将竭尽全力, 帮助你们把所有的梦想实现<br><br><br>
				<p class="text-right"><strong>Friday, August 11, 2017</strong></p>
			</div>
		</div>
	</div>
</section>